#!/bin/bash

set -e

mkdir built-root
cd built-root

SRC_DIR=../../..
BUILD_DIR=${SRC_DIR}/build_docker

cp ${BUILD_DIR}/programs/clickhouse .
cp ${SRC_DIR}/programs/server/{config,users}.xml .

strip clickhouse